---
- hosts: all
  connection: "{{ connection | default('ssh') }}"  # So we can use 'local' for localhost

  # vars:
  #   ...

  tasks:
  - name: Upgrade all apt packages
    become: true
    apt:
      update_cache=yes
      cache_valid_time=3600
      force_apt_get=yes

    ## todo: Also add upstream for Docker: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
  - name: Add Python repository repository from PPA and install its signing key on Ubuntu target
    apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present

  - name: install common packages
    become: true
    apt:
      name:
        - awscli
        - unzip
        - python3.9
        - python3.10
        - python3.11
        - python3.12
        # - docker-ce
        # - docker-ce-cli
        # - containerd.io
        # - docker-buildx-plugin
        # - docker-compose-plugin
      state: latest

  - name: Add default user to `docker` group, so we can use docker w/o sudo
    become: true
    user:
      name: "{{ username }}"
      groups: "{{ username }},docker"
