---
- hosts: all
  become: true
  connection: "{{ connection | default('ssh') }}"  # So we can use 'local' for localhost

  # vars:
  #   ...

  tasks:
  - name: Upgrade all apt packages
    apt:
      update_cache=yes
      cache_valid_time=3600
      force_apt_get=yes

  - name: install common packages
    apt:
      name:
        - awscli
        - unzip
        ## todo: Add upstream for Docker: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
        # - docker-ce
        # - docker-ce-cli
        # - containerd.io
        # - docker-buildx-plugin
        # - docker-compose-plugin
      state: latest

  - name: Add default user to `docker` group, so we can use docker w/o sudo
    user:
      name: "{{ username }}"
      groups: "{{ username }},docker"
