---
- hosts: all
  connection: "{{ connection | default('ssh') }}"  # So we can use 'local' for localhost

  tasks:
  - name: Remove Python installed with APT
    become: true
    apt:
      name:
        # See here how Python is broken up into multiple packages: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
        # I.e., even DeadSnakes repo follows Debian's convention of having multiple packages for each Python version.
        - "python{{ item }}"
        - "python{{ item }}-full"
        - "python{{ item }}-dev"
        - "python{{ item }}-venv"
        - "python{{ item }}-distutils"
      state: absent
    loop:
      # 3.8 is oldest version that still receives security support, as of Aug 2023. Remove Oct 2024.
      - "3.8"
      - "3.9"
      # - "3.10"  # Leave this as system python
      - "3.11"
      - "3.12"
    register: apt_python_packages_removed

  - name: Remove  PPA APT repo
    apt_repository:
      repo: ppa:deadsnakes/ppa
      state: absent
    register: apt_python_repo_removed
