# Usage: source use_conda.sh
# Todo: Don't hardcode user-directory. Can't simply use variable substitution (`~` or `$HOME`) because it is within single quotes!
echo "Initializing Conda."

# generated by Git for Windows
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
eval "$('/c/Users/tloeb/Anaconda3/Scripts/conda.exe' 'shell.bash' 'hook')"

if [ -f "/c/Users/tloeb/Anaconda3/etc/profile.d/conda.sh" ]; then
    . "/c/Users/tloeb/Anaconda3/etc/profile.d/conda.sh"
fi
# <<< conda initialize <<<

# In addition, load IDE-specific env variables
source ~/.env_IDE
